apiVersion: v1
kind: Service
metadata:
  name: spark-worker-service
  labels:
    app: spark-worker
spec:
  type: LoadBalancer
  selector:
    app: spark-worker
  ports:
    # the port that this service should serve on
  - name: context-worker-webui
    port: 4041
    targetPort: 4040
  - name: spark2
    port: 7078
    targetPort: 7078
  - name: worker-webui
    port: 8081
    targetPort: 8081