apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  labels:
    app: clickhouse
spec:
  type: LoadBalancer
  selector:
    app: clickhouse
  ports:
    # the port that this service should serve on
  - name: clickhouse-tcp
    port: 8123
    targetPort: 8123
  - name: clickhouse-http
    port: 9000
    targetPort: 9000
  - name: clickhouse-http-internal
    port: 9009
    targetPort: 9009